import type { ComponentRole } from './types';

// --- Shape Types ---

export type IconShape =
  | 'circle'
  | 'rect'
  | 'cylinder'
  | 'hexagon'
  | 'diamond'
  | 'shield'
  | 'cloud'
  | 'parallelogram';

// --- Category Types ---

export type BlockCategory =
  | 'client'
  | 'compute'
  | 'storage'
  | 'caching'
  | 'messaging'
  | 'networking'
  | 'security'
  | 'monitoring'
  | 'data'
  | 'external'
  | 'entity-relation';

export interface BlockVisual {
  shape: IconShape;
  /** Full Tailwind class literal — e.g. 'bg-blue-600'. Never interpolated. */
  bgClass: string;
  borderClass: string;
  iconColorClass: string;
  svgViewBox?: string;
  /** SVG path `d` attributes (Heroicons 24/solid or Lucide). */
  svgPaths: string[];
  svgFillRule?: 'evenodd' | 'nonzero';
  /** Escape hatch for CSS-constructed visuals that can't be expressed as SVG paths. */
  complexVisualKey?: string;
  /** Name of an exported component from aws-icons.tsx or a Lucide icon name. */
  iconComponent?: string;
  /** Which icon library the iconComponent comes from. */
  iconLibrary?: 'aws' | 'lucide';
}

export interface BlockDefinition {
  /** Stable kebab-case key — serialized to localStorage. Never change after release. */
  kind: string;
  label: string;
  category: BlockCategory;
  sortOrder: number;
  role: ComponentRole;
  defaultWidth: number;
  defaultHeight: number;
  minWidth: number;
  minHeight: number;
  visual: BlockVisual;
}

export interface CategoryMeta {
  id: BlockCategory;
  label: string;
  defaultOpen: boolean;
  blocks: BlockDefinition[];
}

// --- Registry Array ---
// All Tailwind color classes are written as complete string literals so Tailwind's
// content scanner can find them at build time (no dynamic interpolation).

const REGISTRY_ARRAY: BlockDefinition[] = [
  // ─── Clients & Devices ────────────────────────────────────────────────────

  {
    kind: 'user',
    label: 'User',
    category: 'client',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 80,
    defaultHeight: 96,
    minWidth: 80,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-sky-700',
      borderClass: 'border-sky-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'User',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'browser',
    label: 'Browser',
    category: 'client',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 80,
    minHeight: 80,
    visual: {
      shape: 'rect',
      bgClass: 'bg-sky-700',
      borderClass: 'border-sky-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'MonitorSmartphone',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'mobile-app',
    label: 'Mobile App',
    category: 'client',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 80,
    defaultHeight: 96,
    minWidth: 72,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-sky-700',
      borderClass: 'border-sky-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Smartphone',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'desktop-app',
    label: 'Desktop App',
    category: 'client',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-sky-700',
      borderClass: 'border-sky-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Monitor',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'iot-device',
    label: 'IoT Device',
    category: 'client',
    sortOrder: 4,
    role: 'entity',
    defaultWidth: 88,
    defaultHeight: 96,
    minWidth: 80,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-sky-700',
      borderClass: 'border-sky-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Cpu',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'cli',
    label: 'CLI',
    category: 'client',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 88,
    defaultHeight: 96,
    minWidth: 80,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-sky-700',
      borderClass: 'border-sky-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Terminal',
      iconLibrary: 'lucide',
    },
  },

  // ─── Compute & Servers ────────────────────────────────────────────────────

  {
    kind: 'web-server',
    label: 'Web Server',
    category: 'compute',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 128,
    defaultHeight: 96,
    minWidth: 128,
    minHeight: 96,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      complexVisualKey: 'server-rack',
    },
  },
  {
    kind: 'api-gateway',
    label: 'API Gateway',
    category: 'compute',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsApiGateway',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'load-balancer',
    label: 'Load Balancer',
    category: 'compute',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsLoadBalancer',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'container',
    label: 'Container',
    category: 'compute',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsEC2',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'serverless-fn',
    label: 'Lambda / Fn',
    category: 'compute',
    sortOrder: 4,
    role: 'process',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-transparent',
      borderClass: 'border-transparent',
      iconColorClass: 'text-white',
      svgPaths: [],
      complexVisualKey: 'aws-lambda',
    },
  },
  {
    kind: 'vm',
    label: 'Virtual Machine',
    category: 'compute',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsEC2',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'k8s-pod',
    label: 'K8s Pod',
    category: 'compute',
    sortOrder: 6,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsEKS',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'microservice',
    label: 'Microservice',
    category: 'compute',
    sortOrder: 7,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Blocks',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'reverse-proxy',
    label: 'Reverse Proxy',
    category: 'compute',
    sortOrder: 8,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'ArrowLeftRight',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'worker',
    label: 'Worker',
    category: 'compute',
    sortOrder: 9,
    role: 'process',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-violet-700',
      borderClass: 'border-violet-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Cog',
      iconLibrary: 'lucide',
    },
  },

  // ─── Storage & Databases ──────────────────────────────────────────────────

  {
    kind: 'database',
    label: 'Database',
    category: 'storage',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Database',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'sql-db',
    label: 'SQL Database',
    category: 'storage',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsRDS',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'nosql-db',
    label: 'NoSQL Database',
    category: 'storage',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsDynamoDB',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'object-storage',
    label: 'Object Storage',
    category: 'storage',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsS3',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'file-storage',
    label: 'File Storage',
    category: 'storage',
    sortOrder: 4,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsEFS',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'data-warehouse',
    label: 'Data Warehouse',
    category: 'storage',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsRedshift',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'data-lake',
    label: 'Data Lake',
    category: 'storage',
    sortOrder: 6,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsDataLake',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'blob-storage',
    label: 'Blob Storage',
    category: 'storage',
    sortOrder: 7,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-emerald-700',
      borderClass: 'border-emerald-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsS3',
      iconLibrary: 'aws',
    },
  },

  // ─── Caching ──────────────────────────────────────────────────────────────

  {
    kind: 'cache',
    label: 'Cache',
    category: 'caching',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-red-700',
      borderClass: 'border-red-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsElastiCache',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'redis',
    label: 'Redis',
    category: 'caching',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-red-700',
      borderClass: 'border-red-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsElastiCache',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'cdn',
    label: 'CDN',
    category: 'caching',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-red-700',
      borderClass: 'border-red-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsCloudFront',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'browser-cache',
    label: 'Browser Cache',
    category: 'caching',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 88,
    defaultHeight: 96,
    minWidth: 80,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-red-700',
      borderClass: 'border-red-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Clock',
      iconLibrary: 'lucide',
    },
  },

  // ─── Messaging & Events ───────────────────────────────────────────────────

  {
    kind: 'message-queue',
    label: 'Message Queue',
    category: 'messaging',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 120,
    defaultHeight: 96,
    minWidth: 112,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-amber-700',
      borderClass: 'border-amber-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsSQS',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'pub-sub',
    label: 'Pub / Sub',
    category: 'messaging',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-amber-700',
      borderClass: 'border-amber-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsSNS',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'event-bus',
    label: 'Event Bus',
    category: 'messaging',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 120,
    defaultHeight: 96,
    minWidth: 112,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-amber-700',
      borderClass: 'border-amber-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsEventBridge',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'stream-processor',
    label: 'Stream Processor',
    category: 'messaging',
    sortOrder: 3,
    role: 'process',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-amber-700',
      borderClass: 'border-amber-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsKinesis',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'webhook',
    label: 'Webhook',
    category: 'messaging',
    sortOrder: 4,
    role: 'process',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-amber-700',
      borderClass: 'border-amber-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Webhook',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'notification-service',
    label: 'Notification',
    category: 'messaging',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-amber-700',
      borderClass: 'border-amber-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsSNS',
      iconLibrary: 'aws',
    },
  },

  // ─── Networking & Infrastructure ──────────────────────────────────────────

  {
    kind: 'internet',
    label: 'Internet',
    category: 'networking',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-slate-700',
      borderClass: 'border-slate-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Globe',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'dns',
    label: 'DNS',
    category: 'networking',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-slate-700',
      borderClass: 'border-slate-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsRoute53',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'firewall',
    label: 'Firewall',
    category: 'networking',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-slate-700',
      borderClass: 'border-slate-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'ShieldAlert',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'vpc',
    label: 'VPC',
    category: 'networking',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 128,
    defaultHeight: 128,
    minWidth: 120,
    minHeight: 120,
    visual: {
      shape: 'rect',
      bgClass: 'bg-slate-700',
      borderClass: 'border-slate-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsVPC',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'subnet',
    label: 'Subnet',
    category: 'networking',
    sortOrder: 4,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-slate-700',
      borderClass: 'border-slate-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Network',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'availability-zone',
    label: 'Availability Zone',
    category: 'networking',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 120,
    defaultHeight: 96,
    minWidth: 112,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-slate-700',
      borderClass: 'border-slate-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'MapPin',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'region',
    label: 'Region',
    category: 'networking',
    sortOrder: 6,
    role: 'entity',
    defaultWidth: 128,
    defaultHeight: 96,
    minWidth: 120,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-slate-700',
      borderClass: 'border-slate-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Globe2',
      iconLibrary: 'lucide',
    },
  },

  // ─── Security & Identity ──────────────────────────────────────────────────

  {
    kind: 'auth-service',
    label: 'Auth Service',
    category: 'security',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-rose-700',
      borderClass: 'border-rose-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Lock',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'waf',
    label: 'WAF',
    category: 'security',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-rose-700',
      borderClass: 'border-rose-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsWAF',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'encryption',
    label: 'Encryption',
    category: 'security',
    sortOrder: 2,
    role: 'process',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-rose-700',
      borderClass: 'border-rose-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'KeyRound',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'certificate',
    label: 'Certificate',
    category: 'security',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-rose-700',
      borderClass: 'border-rose-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'BadgeCheck',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'secrets-manager',
    label: 'Secrets Manager',
    category: 'security',
    sortOrder: 4,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-rose-700',
      borderClass: 'border-rose-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsSecretsManager',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'iam',
    label: 'IAM',
    category: 'security',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-rose-700',
      borderClass: 'border-rose-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsIAM',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'oauth',
    label: 'OAuth',
    category: 'security',
    sortOrder: 6,
    role: 'process',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-rose-700',
      borderClass: 'border-rose-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsCognito',
      iconLibrary: 'aws',
    },
  },

  // ─── Monitoring & Observability ───────────────────────────────────────────

  {
    kind: 'logging',
    label: 'Logging',
    category: 'monitoring',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-indigo-700',
      borderClass: 'border-indigo-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsCloudWatch',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'metrics',
    label: 'Metrics',
    category: 'monitoring',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-indigo-700',
      borderClass: 'border-indigo-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsCloudWatch',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'alerting',
    label: 'Alerting',
    category: 'monitoring',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-indigo-700',
      borderClass: 'border-indigo-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'BellRing',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'tracing',
    label: 'Tracing',
    category: 'monitoring',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-indigo-700',
      borderClass: 'border-indigo-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsCloudTrail',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'health-check',
    label: 'Health Check',
    category: 'monitoring',
    sortOrder: 4,
    role: 'process',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-indigo-700',
      borderClass: 'border-indigo-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'HeartPulse',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'dashboard',
    label: 'Dashboard',
    category: 'monitoring',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 112,
    defaultHeight: 96,
    minWidth: 104,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-indigo-700',
      borderClass: 'border-indigo-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'LayoutDashboard',
      iconLibrary: 'lucide',
    },
  },

  // ─── Data Processing ──────────────────────────────────────────────────────

  {
    kind: 'etl-pipeline',
    label: 'ETL Pipeline',
    category: 'data',
    sortOrder: 0,
    role: 'process',
    defaultWidth: 120,
    defaultHeight: 96,
    minWidth: 112,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-cyan-700',
      borderClass: 'border-cyan-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsGlue',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'search-engine',
    label: 'Search Engine',
    category: 'data',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-cyan-700',
      borderClass: 'border-cyan-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsOpenSearch',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'graph-db',
    label: 'Graph Database',
    category: 'data',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-cyan-700',
      borderClass: 'border-cyan-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Share2',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'time-series-db',
    label: 'Time-Series DB',
    category: 'data',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-cyan-700',
      borderClass: 'border-cyan-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'TrendingUp',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'data-pipeline',
    label: 'Data Pipeline',
    category: 'data',
    sortOrder: 4,
    role: 'process',
    defaultWidth: 120,
    defaultHeight: 96,
    minWidth: 112,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-cyan-700',
      borderClass: 'border-cyan-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsGlue',
      iconLibrary: 'aws',
    },
  },

  // ─── Entity Relation ─────────────────────────────────────────────────────

  {
    kind: 'entity-relation-table',
    label: 'Table',
    category: 'entity-relation',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 240,
    defaultHeight: 182,
    minWidth: 200,
    minHeight: 182,
    visual: {
      shape: 'rect',
      bgClass: 'bg-transparent',
      borderClass: 'border-white/70',
      iconColorClass: 'text-white',
      svgPaths: [],
      complexVisualKey: 'entity-relation-table',
    },
  },

  // ─── External Services ────────────────────────────────────────────────────

  {
    kind: 'third-party-api',
    label: '3rd Party API',
    category: 'external',
    sortOrder: 0,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-gray-700',
      borderClass: 'border-gray-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'Plug',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'email-service',
    label: 'Email Service',
    category: 'external',
    sortOrder: 1,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-gray-700',
      borderClass: 'border-gray-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsSES',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'sms-service',
    label: 'SMS Service',
    category: 'external',
    sortOrder: 2,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-gray-700',
      borderClass: 'border-gray-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'MessageSquare',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'payment-gateway',
    label: 'Payment Gateway',
    category: 'external',
    sortOrder: 3,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-gray-700',
      borderClass: 'border-gray-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'CreditCard',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'analytics',
    label: 'Analytics',
    category: 'external',
    sortOrder: 4,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-gray-700',
      borderClass: 'border-gray-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'BarChart3',
      iconLibrary: 'lucide',
    },
  },
  {
    kind: 'identity-provider',
    label: 'Identity Provider',
    category: 'external',
    sortOrder: 5,
    role: 'entity',
    defaultWidth: 104,
    defaultHeight: 96,
    minWidth: 96,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-gray-700',
      borderClass: 'border-gray-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsCognito',
      iconLibrary: 'aws',
    },
  },
  {
    kind: 'storage-provider',
    label: 'Cloud Storage',
    category: 'external',
    sortOrder: 6,
    role: 'entity',
    defaultWidth: 96,
    defaultHeight: 96,
    minWidth: 88,
    minHeight: 88,
    visual: {
      shape: 'rect',
      bgClass: 'bg-gray-700',
      borderClass: 'border-gray-500',
      iconColorClass: 'text-white',
      svgPaths: [],
      iconComponent: 'AwsS3',
      iconLibrary: 'aws',
    },
  },
];

// --- Build the Map ---

export const BLOCK_REGISTRY: ReadonlyMap<string, BlockDefinition> = new Map(
  REGISTRY_ARRAY.map((def) => [def.kind, def])
);

// --- Helpers ---

export function getBlockDef(kind: string): BlockDefinition | undefined {
  return BLOCK_REGISTRY.get(kind);
}

export function getBlocksByCategory(category: BlockCategory): BlockDefinition[] {
  return REGISTRY_ARRAY.filter((d) => d.category === category).sort(
    (a, b) => a.sortOrder - b.sortOrder
  );
}

const CATEGORY_META: { id: BlockCategory; label: string; defaultOpen: boolean }[] = [
  { id: 'client',     label: 'Clients & Devices',          defaultOpen: true  },
  { id: 'compute',    label: 'Compute & Servers',           defaultOpen: true  },
  { id: 'storage',    label: 'Storage & Databases',         defaultOpen: false },
  { id: 'caching',    label: 'Caching',                     defaultOpen: false },
  { id: 'messaging',  label: 'Messaging & Events',          defaultOpen: false },
  { id: 'networking', label: 'Networking & Infrastructure', defaultOpen: false },
  { id: 'security',   label: 'Security & Identity',         defaultOpen: false },
  { id: 'monitoring', label: 'Monitoring & Observability',  defaultOpen: false },
  { id: 'data',       label: 'Data Processing',             defaultOpen: false },
  { id: 'external',        label: 'External Services',           defaultOpen: false },
  { id: 'entity-relation', label: 'Entity Relation',             defaultOpen: true  },
];

export function getAllCategories(): CategoryMeta[] {
  return CATEGORY_META.map((meta) => ({
    ...meta,
    blocks: getBlocksByCategory(meta.id),
  }));
}
